# Generated by Django 2.2.1 on 2019-06-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Campteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeamScheduledActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Activity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Campteam')),
            ],
        ),
        migrations.CreateModel(
            name='CamperTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Camper')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Campteam')),
            ],
        ),
        migrations.CreateModel(
            name='CamperActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Activity')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campapp.Camper')),
            ],
        ),
    ]
